Image:
  Os: alinux2
HeadNode:
  InstanceType: c5.xlarge
  Ssh:
    KeyName:  fdm-jenkins
  Networking:
    SubnetId: subnet-054c929102b5e4c47
Scheduling:
  Scheduler: plugin
  SchedulerSettings:
    SchedulerDefinition: <PLUGIN_DEFINITION>
    GrantSudoPrivileges: false
    CustomSettings:
      CustomKey1: CustomValue1
  SchedulerQueues:
    - Name: queue1
      Networking:
        SubnetIds:
          - subnet-0a94506a608268ef3
      CustomSettings:
        CustomQueueKey1: CustomValue1
      ComputeResources:
        - Name: cr1
          InstanceType: c5.xlarge
          CustomSettings:
            CustomComputeResourceKey1: CustomValue1
DevSettings:
  AmiSearchFilters:
    Owner: '447714826191'
