# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class AmiInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, ami_id=None, os=None, name=None, architecture=None):  # noqa: E501
        """AmiInfo - a model defined in OpenAPI

        :param ami_id: The ami_id of this AmiInfo.  # noqa: E501
        :type ami_id: str
        :param os: The os of this AmiInfo.  # noqa: E501
        :type os: str
        :param name: The name of this AmiInfo.  # noqa: E501
        :type name: str
        :param architecture: The architecture of this AmiInfo.  # noqa: E501
        :type architecture: str
        """
        self.openapi_types = {
            'ami_id': str,
            'os': str,
            'name': str,
            'architecture': str
        }

        self.attribute_map = {
            'ami_id': 'amiId',
            'os': 'os',
            'name': 'name',
            'architecture': 'architecture'
        }

        self._ami_id = ami_id
        self._os = os
        self._name = name
        self._architecture = architecture

    @classmethod
    def from_dict(cls, dikt) -> 'AmiInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AmiInfo of this AmiInfo.  # noqa: E501
        :rtype: AmiInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ami_id(self):
        """Gets the ami_id of this AmiInfo.


        :return: The ami_id of this AmiInfo.
        :rtype: str
        """
        return self._ami_id

    @ami_id.setter
    def ami_id(self, ami_id):
        """Sets the ami_id of this AmiInfo.


        :param ami_id: The ami_id of this AmiInfo.
        :type ami_id: str
        """
        if ami_id is None:
            raise ValueError("Invalid value for `ami_id`, must not be `None`")  # noqa: E501

        self._ami_id = ami_id

    @property
    def os(self):
        """Gets the os of this AmiInfo.


        :return: The os of this AmiInfo.
        :rtype: str
        """
        return self._os

    @os.setter
    def os(self, os):
        """Sets the os of this AmiInfo.


        :param os: The os of this AmiInfo.
        :type os: str
        """
        if os is None:
            raise ValueError("Invalid value for `os`, must not be `None`")  # noqa: E501

        self._os = os

    @property
    def name(self):
        """Gets the name of this AmiInfo.


        :return: The name of this AmiInfo.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AmiInfo.


        :param name: The name of this AmiInfo.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def architecture(self):
        """Gets the architecture of this AmiInfo.


        :return: The architecture of this AmiInfo.
        :rtype: str
        """
        return self._architecture

    @architecture.setter
    def architecture(self, architecture):
        """Sets the architecture of this AmiInfo.


        :param architecture: The architecture of this AmiInfo.
        :type architecture: str
        """
        if architecture is None:
            raise ValueError("Invalid value for `architecture`, must not be `None`")  # noqa: E501

        self._architecture = architecture
