# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
import re
from openapi_server import util

import re  # noqa: E501

class BuildImageRequestContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, image_configuration=None, name=None, region=None):  # noqa: E501
        """BuildImageRequestContent - a model defined in OpenAPI

        :param image_configuration: The image_configuration of this BuildImageRequestContent.  # noqa: E501
        :type image_configuration: bytearray
        :param name: The name of this BuildImageRequestContent.  # noqa: E501
        :type name: str
        :param region: The region of this BuildImageRequestContent.  # noqa: E501
        :type region: str
        """
        self.openapi_types = {
            'image_configuration': bytearray,
            'name': str,
            'region': str
        }

        self.attribute_map = {
            'image_configuration': 'imageConfiguration',
            'name': 'name',
            'region': 'region'
        }

        self._image_configuration = image_configuration
        self._name = name
        self._region = region

    @classmethod
    def from_dict(cls, dikt) -> 'BuildImageRequestContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BuildImageRequestContent of this BuildImageRequestContent.  # noqa: E501
        :rtype: BuildImageRequestContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def image_configuration(self):
        """Gets the image_configuration of this BuildImageRequestContent.

        Image configuration as a YAML document  # noqa: E501

        :return: The image_configuration of this BuildImageRequestContent.
        :rtype: bytearray
        """
        return self._image_configuration

    @image_configuration.setter
    def image_configuration(self, image_configuration):
        """Sets the image_configuration of this BuildImageRequestContent.

        Image configuration as a YAML document  # noqa: E501

        :param image_configuration: The image_configuration of this BuildImageRequestContent.
        :type image_configuration: bytearray
        """
        if image_configuration is None:
            raise ValueError("Invalid value for `image_configuration`, must not be `None`")  # noqa: E501

        self._image_configuration = image_configuration

    @property
    def name(self):
        """Gets the name of this BuildImageRequestContent.

        Name of the image  # noqa: E501

        :return: The name of this BuildImageRequestContent.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this BuildImageRequestContent.

        Name of the image  # noqa: E501

        :param name: The name of this BuildImageRequestContent.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) > 60:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `60`")  # noqa: E501
        if name is not None and len(name) < 5:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `5`")  # noqa: E501
        if name is not None and not re.search(r'^[a-zA-Z][a-zA-Z0-9-]+$', name):  # noqa: E501
            raise ValueError("Invalid value for `name`, must be a follow pattern or equal to `/^[a-zA-Z][a-zA-Z0-9-]+$/`")  # noqa: E501

        self._name = name

    @property
    def region(self):
        """Gets the region of this BuildImageRequestContent.

        AWS Region  # noqa: E501

        :return: The region of this BuildImageRequestContent.
        :rtype: str
        """
        return self._region

    @region.setter
    def region(self, region):
        """Sets the region of this BuildImageRequestContent.

        AWS Region  # noqa: E501

        :param region: The region of this BuildImageRequestContent.
        :type region: str
        """
        if region is None:
            raise ValueError("Invalid value for `region`, must not be `None`")  # noqa: E501

        self._region = region
