# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.cloud_formation_status import CloudFormationStatus
from openapi_server.models.cluster_status import ClusterStatus
import re
from openapi_server import util

from openapi_server.models.cloud_formation_status import CloudFormationStatus  # noqa: E501
from openapi_server.models.cluster_status import ClusterStatus  # noqa: E501
import re  # noqa: E501

class ClusterInfoSummary(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, cloudformation_stack_status=None, cloudformation_stack_arn=None, cluster_id=None, region=None, version=None, cluster_status=None):  # noqa: E501
        """ClusterInfoSummary - a model defined in OpenAPI

        :param cloudformation_stack_status: The cloudformation_stack_status of this ClusterInfoSummary.  # noqa: E501
        :type cloudformation_stack_status: CloudFormationStatus
        :param cloudformation_stack_arn: The cloudformation_stack_arn of this ClusterInfoSummary.  # noqa: E501
        :type cloudformation_stack_arn: str
        :param cluster_id: The cluster_id of this ClusterInfoSummary.  # noqa: E501
        :type cluster_id: str
        :param region: The region of this ClusterInfoSummary.  # noqa: E501
        :type region: str
        :param version: The version of this ClusterInfoSummary.  # noqa: E501
        :type version: str
        :param cluster_status: The cluster_status of this ClusterInfoSummary.  # noqa: E501
        :type cluster_status: ClusterStatus
        """
        self.openapi_types = {
            'cloudformation_stack_status': CloudFormationStatus,
            'cloudformation_stack_arn': str,
            'cluster_id': str,
            'region': str,
            'version': str,
            'cluster_status': ClusterStatus
        }

        self.attribute_map = {
            'cloudformation_stack_status': 'cloudformationStackStatus',
            'cloudformation_stack_arn': 'cloudformationStackArn',
            'cluster_id': 'clusterId',
            'region': 'region',
            'version': 'version',
            'cluster_status': 'clusterStatus'
        }

        self._cloudformation_stack_status = cloudformation_stack_status
        self._cloudformation_stack_arn = cloudformation_stack_arn
        self._cluster_id = cluster_id
        self._region = region
        self._version = version
        self._cluster_status = cluster_status

    @classmethod
    def from_dict(cls, dikt) -> 'ClusterInfoSummary':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ClusterInfoSummary of this ClusterInfoSummary.  # noqa: E501
        :rtype: ClusterInfoSummary
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cloudformation_stack_status(self):
        """Gets the cloudformation_stack_status of this ClusterInfoSummary.


        :return: The cloudformation_stack_status of this ClusterInfoSummary.
        :rtype: CloudFormationStatus
        """
        return self._cloudformation_stack_status

    @cloudformation_stack_status.setter
    def cloudformation_stack_status(self, cloudformation_stack_status):
        """Sets the cloudformation_stack_status of this ClusterInfoSummary.


        :param cloudformation_stack_status: The cloudformation_stack_status of this ClusterInfoSummary.
        :type cloudformation_stack_status: CloudFormationStatus
        """
        if cloudformation_stack_status is None:
            raise ValueError("Invalid value for `cloudformation_stack_status`, must not be `None`")  # noqa: E501

        self._cloudformation_stack_status = cloudformation_stack_status

    @property
    def cloudformation_stack_arn(self):
        """Gets the cloudformation_stack_arn of this ClusterInfoSummary.

        ARN of the main CloudFormation stack  # noqa: E501

        :return: The cloudformation_stack_arn of this ClusterInfoSummary.
        :rtype: str
        """
        return self._cloudformation_stack_arn

    @cloudformation_stack_arn.setter
    def cloudformation_stack_arn(self, cloudformation_stack_arn):
        """Sets the cloudformation_stack_arn of this ClusterInfoSummary.

        ARN of the main CloudFormation stack  # noqa: E501

        :param cloudformation_stack_arn: The cloudformation_stack_arn of this ClusterInfoSummary.
        :type cloudformation_stack_arn: str
        """
        if cloudformation_stack_arn is None:
            raise ValueError("Invalid value for `cloudformation_stack_arn`, must not be `None`")  # noqa: E501

        self._cloudformation_stack_arn = cloudformation_stack_arn

    @property
    def cluster_id(self):
        """Gets the cluster_id of this ClusterInfoSummary.

        Name of the cluster  # noqa: E501

        :return: The cluster_id of this ClusterInfoSummary.
        :rtype: str
        """
        return self._cluster_id

    @cluster_id.setter
    def cluster_id(self, cluster_id):
        """Sets the cluster_id of this ClusterInfoSummary.

        Name of the cluster  # noqa: E501

        :param cluster_id: The cluster_id of this ClusterInfoSummary.
        :type cluster_id: str
        """
        if cluster_id is None:
            raise ValueError("Invalid value for `cluster_id`, must not be `None`")  # noqa: E501
        if cluster_id is not None and len(cluster_id) > 60:
            raise ValueError("Invalid value for `cluster_id`, length must be less than or equal to `60`")  # noqa: E501
        if cluster_id is not None and len(cluster_id) < 5:
            raise ValueError("Invalid value for `cluster_id`, length must be greater than or equal to `5`")  # noqa: E501
        if cluster_id is not None and not re.search(r'^[a-zA-Z][a-zA-Z0-9-]+$', cluster_id):  # noqa: E501
            raise ValueError("Invalid value for `cluster_id`, must be a follow pattern or equal to `/^[a-zA-Z][a-zA-Z0-9-]+$/`")  # noqa: E501

        self._cluster_id = cluster_id

    @property
    def region(self):
        """Gets the region of this ClusterInfoSummary.

        AWS region where the cluster is created  # noqa: E501

        :return: The region of this ClusterInfoSummary.
        :rtype: str
        """
        return self._region

    @region.setter
    def region(self, region):
        """Sets the region of this ClusterInfoSummary.

        AWS region where the cluster is created  # noqa: E501

        :param region: The region of this ClusterInfoSummary.
        :type region: str
        """
        if region is None:
            raise ValueError("Invalid value for `region`, must not be `None`")  # noqa: E501

        self._region = region

    @property
    def version(self):
        """Gets the version of this ClusterInfoSummary.

        ParallelCluster version used to create the cluster  # noqa: E501

        :return: The version of this ClusterInfoSummary.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this ClusterInfoSummary.

        ParallelCluster version used to create the cluster  # noqa: E501

        :param version: The version of this ClusterInfoSummary.
        :type version: str
        """
        if version is None:
            raise ValueError("Invalid value for `version`, must not be `None`")  # noqa: E501
        if version is not None and not re.search(r'^[0-9]+\.[0-9]+\.[0-9]+$', version):  # noqa: E501
            raise ValueError("Invalid value for `version`, must be a follow pattern or equal to `/^[0-9]+\.[0-9]+\.[0-9]+$/`")  # noqa: E501

        self._version = version

    @property
    def cluster_status(self):
        """Gets the cluster_status of this ClusterInfoSummary.


        :return: The cluster_status of this ClusterInfoSummary.
        :rtype: ClusterStatus
        """
        return self._cluster_status

    @cluster_status.setter
    def cluster_status(self, cluster_status):
        """Sets the cluster_status of this ClusterInfoSummary.


        :param cluster_status: The cluster_status of this ClusterInfoSummary.
        :type cluster_status: ClusterStatus
        """
        if cluster_status is None:
            raise ValueError("Invalid value for `cluster_status`, must not be `None`")  # noqa: E501

        self._cluster_status = cluster_status
