# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ClusterConfigurationStructure(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None, creation_time=None, version=None):  # noqa: E501
        """ClusterConfigurationStructure - a model defined in OpenAPI

        :param data: The data of this ClusterConfigurationStructure.  # noqa: E501
        :type data: bytearray
        :param creation_time: The creation_time of this ClusterConfigurationStructure.  # noqa: E501
        :type creation_time: str
        :param version: The version of this ClusterConfigurationStructure.  # noqa: E501
        :type version: str
        """
        self.openapi_types = {
            'data': bytearray,
            'creation_time': str,
            'version': str
        }

        self.attribute_map = {
            'data': 'data',
            'creation_time': 'creationTime',
            'version': 'version'
        }

        self._data = data
        self._creation_time = creation_time
        self._version = version

    @classmethod
    def from_dict(cls, dikt) -> 'ClusterConfigurationStructure':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ClusterConfigurationStructure of this ClusterConfigurationStructure.  # noqa: E501
        :rtype: ClusterConfigurationStructure
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this ClusterConfigurationStructure.

        Cluster configuration as a YAML document  # noqa: E501

        :return: The data of this ClusterConfigurationStructure.
        :rtype: bytearray
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this ClusterConfigurationStructure.

        Cluster configuration as a YAML document  # noqa: E501

        :param data: The data of this ClusterConfigurationStructure.
        :type data: bytearray
        """

        self._data = data

    @property
    def creation_time(self):
        """Gets the creation_time of this ClusterConfigurationStructure.


        :return: The creation_time of this ClusterConfigurationStructure.
        :rtype: str
        """
        return self._creation_time

    @creation_time.setter
    def creation_time(self, creation_time):
        """Sets the creation_time of this ClusterConfigurationStructure.


        :param creation_time: The creation_time of this ClusterConfigurationStructure.
        :type creation_time: str
        """

        self._creation_time = creation_time

    @property
    def version(self):
        """Gets the version of this ClusterConfigurationStructure.


        :return: The version of this ClusterConfigurationStructure.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this ClusterConfigurationStructure.


        :param version: The version of this ClusterConfigurationStructure.
        :type version: str
        """

        self._version = version
