# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ClusterConfigurationSummary(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, creation_time=None, version=None):  # noqa: E501
        """ClusterConfigurationSummary - a model defined in OpenAPI

        :param creation_time: The creation_time of this ClusterConfigurationSummary.  # noqa: E501
        :type creation_time: str
        :param version: The version of this ClusterConfigurationSummary.  # noqa: E501
        :type version: str
        """
        self.openapi_types = {
            'creation_time': str,
            'version': str
        }

        self.attribute_map = {
            'creation_time': 'creationTime',
            'version': 'version'
        }

        self._creation_time = creation_time
        self._version = version

    @classmethod
    def from_dict(cls, dikt) -> 'ClusterConfigurationSummary':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ClusterConfigurationSummary of this ClusterConfigurationSummary.  # noqa: E501
        :rtype: ClusterConfigurationSummary
        """
        return util.deserialize_model(dikt, cls)

    @property
    def creation_time(self):
        """Gets the creation_time of this ClusterConfigurationSummary.


        :return: The creation_time of this ClusterConfigurationSummary.
        :rtype: str
        """
        return self._creation_time

    @creation_time.setter
    def creation_time(self, creation_time):
        """Sets the creation_time of this ClusterConfigurationSummary.


        :param creation_time: The creation_time of this ClusterConfigurationSummary.
        :type creation_time: str
        """

        self._creation_time = creation_time

    @property
    def version(self):
        """Gets the version of this ClusterConfigurationSummary.


        :return: The version of this ClusterConfigurationSummary.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this ClusterConfigurationSummary.


        :param version: The version of this ClusterConfigurationSummary.
        :type version: str
        """

        self._version = version
