# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ComputeFleetStatus(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    START_REQUESTED = "START_REQUESTED"
    STARTING = "STARTING"
    RUNNING = "RUNNING"
    STOP_REQUESTED = "STOP_REQUESTED"
    STOPPING = "STOPPING"
    STOPPED = "STOPPED"
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"
    def __init__(self):  # noqa: E501
        """ComputeFleetStatus - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ComputeFleetStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ComputeFleetStatus of this ComputeFleetStatus.  # noqa: E501
        :rtype: ComputeFleetStatus
        """
        return util.deserialize_model(dikt, cls)
