# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
import re
from openapi_server import util

import re  # noqa: E501

class CreateClusterRequestContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, region=None, cluster_configuration=None):  # noqa: E501
        """CreateClusterRequestContent - a model defined in OpenAPI

        :param name: The name of this CreateClusterRequestContent.  # noqa: E501
        :type name: str
        :param region: The region of this CreateClusterRequestContent.  # noqa: E501
        :type region: str
        :param cluster_configuration: The cluster_configuration of this CreateClusterRequestContent.  # noqa: E501
        :type cluster_configuration: bytearray
        """
        self.openapi_types = {
            'name': str,
            'region': str,
            'cluster_configuration': bytearray
        }

        self.attribute_map = {
            'name': 'name',
            'region': 'region',
            'cluster_configuration': 'clusterConfiguration'
        }

        self._name = name
        self._region = region
        self._cluster_configuration = cluster_configuration

    @classmethod
    def from_dict(cls, dikt) -> 'CreateClusterRequestContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateClusterRequestContent of this CreateClusterRequestContent.  # noqa: E501
        :rtype: CreateClusterRequestContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this CreateClusterRequestContent.

        Name of the cluster  # noqa: E501

        :return: The name of this CreateClusterRequestContent.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CreateClusterRequestContent.

        Name of the cluster  # noqa: E501

        :param name: The name of this CreateClusterRequestContent.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) > 60:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `60`")  # noqa: E501
        if name is not None and len(name) < 5:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `5`")  # noqa: E501
        if name is not None and not re.search(r'^[a-zA-Z][a-zA-Z0-9-]+$', name):  # noqa: E501
            raise ValueError("Invalid value for `name`, must be a follow pattern or equal to `/^[a-zA-Z][a-zA-Z0-9-]+$/`")  # noqa: E501

        self._name = name

    @property
    def region(self):
        """Gets the region of this CreateClusterRequestContent.

        AWS Region. Defaults to the region the API is deployed to.  # noqa: E501

        :return: The region of this CreateClusterRequestContent.
        :rtype: str
        """
        return self._region

    @region.setter
    def region(self, region):
        """Sets the region of this CreateClusterRequestContent.

        AWS Region. Defaults to the region the API is deployed to.  # noqa: E501

        :param region: The region of this CreateClusterRequestContent.
        :type region: str
        """

        self._region = region

    @property
    def cluster_configuration(self):
        """Gets the cluster_configuration of this CreateClusterRequestContent.

        Cluster configuration as a YAML document  # noqa: E501

        :return: The cluster_configuration of this CreateClusterRequestContent.
        :rtype: bytearray
        """
        return self._cluster_configuration

    @cluster_configuration.setter
    def cluster_configuration(self, cluster_configuration):
        """Sets the cluster_configuration of this CreateClusterRequestContent.

        Cluster configuration as a YAML document  # noqa: E501

        :param cluster_configuration: The cluster_configuration of this CreateClusterRequestContent.
        :type cluster_configuration: bytearray
        """
        if cluster_configuration is None:
            raise ValueError("Invalid value for `cluster_configuration`, must not be `None`")  # noqa: E501

        self._cluster_configuration = cluster_configuration
