# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class DescribeDcvSessionManagerEndpointResponseContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, client_id=None, client_secret=None, session_manager_endpoint=None):  # noqa: E501
        """DescribeDcvSessionManagerEndpointResponseContent - a model defined in OpenAPI

        :param client_id: The client_id of this DescribeDcvSessionManagerEndpointResponseContent.  # noqa: E501
        :type client_id: str
        :param client_secret: The client_secret of this DescribeDcvSessionManagerEndpointResponseContent.  # noqa: E501
        :type client_secret: str
        :param session_manager_endpoint: The session_manager_endpoint of this DescribeDcvSessionManagerEndpointResponseContent.  # noqa: E501
        :type session_manager_endpoint: str
        """
        self.openapi_types = {
            'client_id': str,
            'client_secret': str,
            'session_manager_endpoint': str
        }

        self.attribute_map = {
            'client_id': 'clientId',
            'client_secret': 'clientSecret',
            'session_manager_endpoint': 'sessionManagerEndpoint'
        }

        self._client_id = client_id
        self._client_secret = client_secret
        self._session_manager_endpoint = session_manager_endpoint

    @classmethod
    def from_dict(cls, dikt) -> 'DescribeDcvSessionManagerEndpointResponseContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DescribeDcvSessionManagerEndpointResponseContent of this DescribeDcvSessionManagerEndpointResponseContent.  # noqa: E501
        :rtype: DescribeDcvSessionManagerEndpointResponseContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def client_id(self):
        """Gets the client_id of this DescribeDcvSessionManagerEndpointResponseContent.


        :return: The client_id of this DescribeDcvSessionManagerEndpointResponseContent.
        :rtype: str
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id):
        """Sets the client_id of this DescribeDcvSessionManagerEndpointResponseContent.


        :param client_id: The client_id of this DescribeDcvSessionManagerEndpointResponseContent.
        :type client_id: str
        """
        if client_id is None:
            raise ValueError("Invalid value for `client_id`, must not be `None`")  # noqa: E501

        self._client_id = client_id

    @property
    def client_secret(self):
        """Gets the client_secret of this DescribeDcvSessionManagerEndpointResponseContent.


        :return: The client_secret of this DescribeDcvSessionManagerEndpointResponseContent.
        :rtype: str
        """
        return self._client_secret

    @client_secret.setter
    def client_secret(self, client_secret):
        """Sets the client_secret of this DescribeDcvSessionManagerEndpointResponseContent.


        :param client_secret: The client_secret of this DescribeDcvSessionManagerEndpointResponseContent.
        :type client_secret: str
        """
        if client_secret is None:
            raise ValueError("Invalid value for `client_secret`, must not be `None`")  # noqa: E501

        self._client_secret = client_secret

    @property
    def session_manager_endpoint(self):
        """Gets the session_manager_endpoint of this DescribeDcvSessionManagerEndpointResponseContent.

        https://<broker-hostname>:<port>  # noqa: E501

        :return: The session_manager_endpoint of this DescribeDcvSessionManagerEndpointResponseContent.
        :rtype: str
        """
        return self._session_manager_endpoint

    @session_manager_endpoint.setter
    def session_manager_endpoint(self, session_manager_endpoint):
        """Sets the session_manager_endpoint of this DescribeDcvSessionManagerEndpointResponseContent.

        https://<broker-hostname>:<port>  # noqa: E501

        :param session_manager_endpoint: The session_manager_endpoint of this DescribeDcvSessionManagerEndpointResponseContent.
        :type session_manager_endpoint: str
        """
        if session_manager_endpoint is None:
            raise ValueError("Invalid value for `session_manager_endpoint`, must not be `None`")  # noqa: E501

        self._session_manager_endpoint = session_manager_endpoint
