# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.cloud_formation_status import CloudFormationStatus
from openapi_server.models.ec2_ami_info import Ec2AmiInfo
from openapi_server.models.image_build_status import ImageBuildStatus
from openapi_server.models.image_builder_image_status import ImageBuilderImageStatus
from openapi_server.models.tag import Tag
import re
from openapi_server import util

from openapi_server.models.cloud_formation_status import CloudFormationStatus  # noqa: E501
from openapi_server.models.ec2_ami_info import Ec2AmiInfo  # noqa: E501
from openapi_server.models.image_build_status import ImageBuildStatus  # noqa: E501
from openapi_server.models.image_builder_image_status import ImageBuilderImageStatus  # noqa: E501
from openapi_server.models.tag import Tag  # noqa: E501
import re  # noqa: E501

class DescribeImageResponseContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, image_configuration=None, image_id=None, imagebuilder_image_status=None, creation_time=None, image_build_status=None, cloudformation_stack_status=None, cloudformation_stack_arn=None, region=None, ec2_ami_info=None, version=None, tags=None):  # noqa: E501
        """DescribeImageResponseContent - a model defined in OpenAPI

        :param image_configuration: The image_configuration of this DescribeImageResponseContent.  # noqa: E501
        :type image_configuration: bytearray
        :param image_id: The image_id of this DescribeImageResponseContent.  # noqa: E501
        :type image_id: str
        :param imagebuilder_image_status: The imagebuilder_image_status of this DescribeImageResponseContent.  # noqa: E501
        :type imagebuilder_image_status: ImageBuilderImageStatus
        :param creation_time: The creation_time of this DescribeImageResponseContent.  # noqa: E501
        :type creation_time: str
        :param image_build_status: The image_build_status of this DescribeImageResponseContent.  # noqa: E501
        :type image_build_status: ImageBuildStatus
        :param cloudformation_stack_status: The cloudformation_stack_status of this DescribeImageResponseContent.  # noqa: E501
        :type cloudformation_stack_status: CloudFormationStatus
        :param cloudformation_stack_arn: The cloudformation_stack_arn of this DescribeImageResponseContent.  # noqa: E501
        :type cloudformation_stack_arn: str
        :param region: The region of this DescribeImageResponseContent.  # noqa: E501
        :type region: str
        :param ec2_ami_info: The ec2_ami_info of this DescribeImageResponseContent.  # noqa: E501
        :type ec2_ami_info: Ec2AmiInfo
        :param version: The version of this DescribeImageResponseContent.  # noqa: E501
        :type version: str
        :param tags: The tags of this DescribeImageResponseContent.  # noqa: E501
        :type tags: List[Tag]
        """
        self.openapi_types = {
            'image_configuration': bytearray,
            'image_id': str,
            'imagebuilder_image_status': ImageBuilderImageStatus,
            'creation_time': str,
            'image_build_status': ImageBuildStatus,
            'cloudformation_stack_status': CloudFormationStatus,
            'cloudformation_stack_arn': str,
            'region': str,
            'ec2_ami_info': Ec2AmiInfo,
            'version': str,
            'tags': List[Tag]
        }

        self.attribute_map = {
            'image_configuration': 'imageConfiguration',
            'image_id': 'imageId',
            'imagebuilder_image_status': 'imagebuilderImageStatus',
            'creation_time': 'creationTime',
            'image_build_status': 'imageBuildStatus',
            'cloudformation_stack_status': 'cloudformationStackStatus',
            'cloudformation_stack_arn': 'cloudformationStackArn',
            'region': 'region',
            'ec2_ami_info': 'ec2AmiInfo',
            'version': 'version',
            'tags': 'tags'
        }

        self._image_configuration = image_configuration
        self._image_id = image_id
        self._imagebuilder_image_status = imagebuilder_image_status
        self._creation_time = creation_time
        self._image_build_status = image_build_status
        self._cloudformation_stack_status = cloudformation_stack_status
        self._cloudformation_stack_arn = cloudformation_stack_arn
        self._region = region
        self._ec2_ami_info = ec2_ami_info
        self._version = version
        self._tags = tags

    @classmethod
    def from_dict(cls, dikt) -> 'DescribeImageResponseContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DescribeImageResponseContent of this DescribeImageResponseContent.  # noqa: E501
        :rtype: DescribeImageResponseContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def image_configuration(self):
        """Gets the image_configuration of this DescribeImageResponseContent.

        Configuration for the image build process  # noqa: E501

        :return: The image_configuration of this DescribeImageResponseContent.
        :rtype: bytearray
        """
        return self._image_configuration

    @image_configuration.setter
    def image_configuration(self, image_configuration):
        """Sets the image_configuration of this DescribeImageResponseContent.

        Configuration for the image build process  # noqa: E501

        :param image_configuration: The image_configuration of this DescribeImageResponseContent.
        :type image_configuration: bytearray
        """
        if image_configuration is None:
            raise ValueError("Invalid value for `image_configuration`, must not be `None`")  # noqa: E501

        self._image_configuration = image_configuration

    @property
    def image_id(self):
        """Gets the image_id of this DescribeImageResponseContent.

        Name of the Image  # noqa: E501

        :return: The image_id of this DescribeImageResponseContent.
        :rtype: str
        """
        return self._image_id

    @image_id.setter
    def image_id(self, image_id):
        """Sets the image_id of this DescribeImageResponseContent.

        Name of the Image  # noqa: E501

        :param image_id: The image_id of this DescribeImageResponseContent.
        :type image_id: str
        """
        if image_id is None:
            raise ValueError("Invalid value for `image_id`, must not be `None`")  # noqa: E501

        self._image_id = image_id

    @property
    def imagebuilder_image_status(self):
        """Gets the imagebuilder_image_status of this DescribeImageResponseContent.


        :return: The imagebuilder_image_status of this DescribeImageResponseContent.
        :rtype: ImageBuilderImageStatus
        """
        return self._imagebuilder_image_status

    @imagebuilder_image_status.setter
    def imagebuilder_image_status(self, imagebuilder_image_status):
        """Sets the imagebuilder_image_status of this DescribeImageResponseContent.


        :param imagebuilder_image_status: The imagebuilder_image_status of this DescribeImageResponseContent.
        :type imagebuilder_image_status: ImageBuilderImageStatus
        """

        self._imagebuilder_image_status = imagebuilder_image_status

    @property
    def creation_time(self):
        """Gets the creation_time of this DescribeImageResponseContent.

        Timestamp representing the image creation time  # noqa: E501

        :return: The creation_time of this DescribeImageResponseContent.
        :rtype: str
        """
        return self._creation_time

    @creation_time.setter
    def creation_time(self, creation_time):
        """Sets the creation_time of this DescribeImageResponseContent.

        Timestamp representing the image creation time  # noqa: E501

        :param creation_time: The creation_time of this DescribeImageResponseContent.
        :type creation_time: str
        """
        if creation_time is None:
            raise ValueError("Invalid value for `creation_time`, must not be `None`")  # noqa: E501

        self._creation_time = creation_time

    @property
    def image_build_status(self):
        """Gets the image_build_status of this DescribeImageResponseContent.


        :return: The image_build_status of this DescribeImageResponseContent.
        :rtype: ImageBuildStatus
        """
        return self._image_build_status

    @image_build_status.setter
    def image_build_status(self, image_build_status):
        """Sets the image_build_status of this DescribeImageResponseContent.


        :param image_build_status: The image_build_status of this DescribeImageResponseContent.
        :type image_build_status: ImageBuildStatus
        """
        if image_build_status is None:
            raise ValueError("Invalid value for `image_build_status`, must not be `None`")  # noqa: E501

        self._image_build_status = image_build_status

    @property
    def cloudformation_stack_status(self):
        """Gets the cloudformation_stack_status of this DescribeImageResponseContent.


        :return: The cloudformation_stack_status of this DescribeImageResponseContent.
        :rtype: CloudFormationStatus
        """
        return self._cloudformation_stack_status

    @cloudformation_stack_status.setter
    def cloudformation_stack_status(self, cloudformation_stack_status):
        """Sets the cloudformation_stack_status of this DescribeImageResponseContent.


        :param cloudformation_stack_status: The cloudformation_stack_status of this DescribeImageResponseContent.
        :type cloudformation_stack_status: CloudFormationStatus
        """
        if cloudformation_stack_status is None:
            raise ValueError("Invalid value for `cloudformation_stack_status`, must not be `None`")  # noqa: E501

        self._cloudformation_stack_status = cloudformation_stack_status

    @property
    def cloudformation_stack_arn(self):
        """Gets the cloudformation_stack_arn of this DescribeImageResponseContent.

        ARN of the main CloudFormation stack  # noqa: E501

        :return: The cloudformation_stack_arn of this DescribeImageResponseContent.
        :rtype: str
        """
        return self._cloudformation_stack_arn

    @cloudformation_stack_arn.setter
    def cloudformation_stack_arn(self, cloudformation_stack_arn):
        """Sets the cloudformation_stack_arn of this DescribeImageResponseContent.

        ARN of the main CloudFormation stack  # noqa: E501

        :param cloudformation_stack_arn: The cloudformation_stack_arn of this DescribeImageResponseContent.
        :type cloudformation_stack_arn: str
        """
        if cloudformation_stack_arn is None:
            raise ValueError("Invalid value for `cloudformation_stack_arn`, must not be `None`")  # noqa: E501

        self._cloudformation_stack_arn = cloudformation_stack_arn

    @property
    def region(self):
        """Gets the region of this DescribeImageResponseContent.

        AWS region where the image is created  # noqa: E501

        :return: The region of this DescribeImageResponseContent.
        :rtype: str
        """
        return self._region

    @region.setter
    def region(self, region):
        """Sets the region of this DescribeImageResponseContent.

        AWS region where the image is created  # noqa: E501

        :param region: The region of this DescribeImageResponseContent.
        :type region: str
        """
        if region is None:
            raise ValueError("Invalid value for `region`, must not be `None`")  # noqa: E501

        self._region = region

    @property
    def ec2_ami_info(self):
        """Gets the ec2_ami_info of this DescribeImageResponseContent.


        :return: The ec2_ami_info of this DescribeImageResponseContent.
        :rtype: Ec2AmiInfo
        """
        return self._ec2_ami_info

    @ec2_ami_info.setter
    def ec2_ami_info(self, ec2_ami_info):
        """Sets the ec2_ami_info of this DescribeImageResponseContent.


        :param ec2_ami_info: The ec2_ami_info of this DescribeImageResponseContent.
        :type ec2_ami_info: Ec2AmiInfo
        """

        self._ec2_ami_info = ec2_ami_info

    @property
    def version(self):
        """Gets the version of this DescribeImageResponseContent.

        ParallelCluster version used to build the image  # noqa: E501

        :return: The version of this DescribeImageResponseContent.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this DescribeImageResponseContent.

        ParallelCluster version used to build the image  # noqa: E501

        :param version: The version of this DescribeImageResponseContent.
        :type version: str
        """
        if version is None:
            raise ValueError("Invalid value for `version`, must not be `None`")  # noqa: E501
        if version is not None and not re.search(r'^[0-9]+\.[0-9]+\.[0-9]+$', version):  # noqa: E501
            raise ValueError("Invalid value for `version`, must be a follow pattern or equal to `/^[0-9]+\.[0-9]+\.[0-9]+$/`")  # noqa: E501

        self._version = version

    @property
    def tags(self):
        """Gets the tags of this DescribeImageResponseContent.

        Tags of the infrastructure to build the Image  # noqa: E501

        :return: The tags of this DescribeImageResponseContent.
        :rtype: List[Tag]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this DescribeImageResponseContent.

        Tags of the infrastructure to build the Image  # noqa: E501

        :param tags: The tags of this DescribeImageResponseContent.
        :type tags: List[Tag]
        """
        if tags is None:
            raise ValueError("Invalid value for `tags`, must not be `None`")  # noqa: E501

        self._tags = tags
