# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
import re
from openapi_server import util

import re  # noqa: E501

class DescribeParallelClusterVersionsResponseContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, enabled_parallel_cluster_versions=None, default_parallel_cluster_version=None):  # noqa: E501
        """DescribeParallelClusterVersionsResponseContent - a model defined in OpenAPI

        :param enabled_parallel_cluster_versions: The enabled_parallel_cluster_versions of this DescribeParallelClusterVersionsResponseContent.  # noqa: E501
        :type enabled_parallel_cluster_versions: List[str]
        :param default_parallel_cluster_version: The default_parallel_cluster_version of this DescribeParallelClusterVersionsResponseContent.  # noqa: E501
        :type default_parallel_cluster_version: str
        """
        self.openapi_types = {
            'enabled_parallel_cluster_versions': List[str],
            'default_parallel_cluster_version': str
        }

        self.attribute_map = {
            'enabled_parallel_cluster_versions': 'enabledParallelClusterVersions',
            'default_parallel_cluster_version': 'defaultParallelClusterVersion'
        }

        self._enabled_parallel_cluster_versions = enabled_parallel_cluster_versions
        self._default_parallel_cluster_version = default_parallel_cluster_version

    @classmethod
    def from_dict(cls, dikt) -> 'DescribeParallelClusterVersionsResponseContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DescribeParallelClusterVersionsResponseContent of this DescribeParallelClusterVersionsResponseContent.  # noqa: E501
        :rtype: DescribeParallelClusterVersionsResponseContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def enabled_parallel_cluster_versions(self):
        """Gets the enabled_parallel_cluster_versions of this DescribeParallelClusterVersionsResponseContent.

        ParallelCluster versions supported by the API.  # noqa: E501

        :return: The enabled_parallel_cluster_versions of this DescribeParallelClusterVersionsResponseContent.
        :rtype: List[str]
        """
        return self._enabled_parallel_cluster_versions

    @enabled_parallel_cluster_versions.setter
    def enabled_parallel_cluster_versions(self, enabled_parallel_cluster_versions):
        """Sets the enabled_parallel_cluster_versions of this DescribeParallelClusterVersionsResponseContent.

        ParallelCluster versions supported by the API.  # noqa: E501

        :param enabled_parallel_cluster_versions: The enabled_parallel_cluster_versions of this DescribeParallelClusterVersionsResponseContent.
        :type enabled_parallel_cluster_versions: List[str]
        """
        if enabled_parallel_cluster_versions is None:
            raise ValueError("Invalid value for `enabled_parallel_cluster_versions`, must not be `None`")  # noqa: E501

        self._enabled_parallel_cluster_versions = enabled_parallel_cluster_versions

    @property
    def default_parallel_cluster_version(self):
        """Gets the default_parallel_cluster_version of this DescribeParallelClusterVersionsResponseContent.

        Default version used when version is not specified in the request.  # noqa: E501

        :return: The default_parallel_cluster_version of this DescribeParallelClusterVersionsResponseContent.
        :rtype: str
        """
        return self._default_parallel_cluster_version

    @default_parallel_cluster_version.setter
    def default_parallel_cluster_version(self, default_parallel_cluster_version):
        """Sets the default_parallel_cluster_version of this DescribeParallelClusterVersionsResponseContent.

        Default version used when version is not specified in the request.  # noqa: E501

        :param default_parallel_cluster_version: The default_parallel_cluster_version of this DescribeParallelClusterVersionsResponseContent.
        :type default_parallel_cluster_version: str
        """
        if default_parallel_cluster_version is None:
            raise ValueError("Invalid value for `default_parallel_cluster_version`, must not be `None`")  # noqa: E501
        if default_parallel_cluster_version is not None and not re.search(r'^[0-9]+\.[0-9]+\.[0-9]+$', default_parallel_cluster_version):  # noqa: E501
            raise ValueError("Invalid value for `default_parallel_cluster_version`, must be a follow pattern or equal to `/^[0-9]+\.[0-9]+\.[0-9]+$/`")  # noqa: E501

        self._default_parallel_cluster_version = default_parallel_cluster_version
