# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.ec2_instance import EC2Instance
from openapi_server import util

from openapi_server.models.ec2_instance import EC2Instance  # noqa: E501

class DescribeClusterInstancesResponseContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, instances=None, next_token=None):  # noqa: E501
        """DescribeClusterInstancesResponseContent - a model defined in OpenAPI

        :param instances: The instances of this DescribeClusterInstancesResponseContent.  # noqa: E501
        :type instances: List[EC2Instance]
        :param next_token: The next_token of this DescribeClusterInstancesResponseContent.  # noqa: E501
        :type next_token: str
        """
        self.openapi_types = {
            'instances': List[EC2Instance],
            'next_token': str
        }

        self.attribute_map = {
            'instances': 'instances',
            'next_token': 'nextToken'
        }

        self._instances = instances
        self._next_token = next_token

    @classmethod
    def from_dict(cls, dikt) -> 'DescribeClusterInstancesResponseContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DescribeClusterInstancesResponseContent of this DescribeClusterInstancesResponseContent.  # noqa: E501
        :rtype: DescribeClusterInstancesResponseContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def instances(self):
        """Gets the instances of this DescribeClusterInstancesResponseContent.


        :return: The instances of this DescribeClusterInstancesResponseContent.
        :rtype: List[EC2Instance]
        """
        return self._instances

    @instances.setter
    def instances(self, instances):
        """Sets the instances of this DescribeClusterInstancesResponseContent.


        :param instances: The instances of this DescribeClusterInstancesResponseContent.
        :type instances: List[EC2Instance]
        """
        if instances is None:
            raise ValueError("Invalid value for `instances`, must not be `None`")  # noqa: E501

        self._instances = instances

    @property
    def next_token(self):
        """Gets the next_token of this DescribeClusterInstancesResponseContent.


        :return: The next_token of this DescribeClusterInstancesResponseContent.
        :rtype: str
        """
        return self._next_token

    @next_token.setter
    def next_token(self, next_token):
        """Sets the next_token of this DescribeClusterInstancesResponseContent.


        :param next_token: The next_token of this DescribeClusterInstancesResponseContent.
        :type next_token: str
        """

        self._next_token = next_token
