# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.cluster_configuration_structure import ClusterConfigurationStructure
from openapi_server import util

from openapi_server.models.cluster_configuration_structure import ClusterConfigurationStructure  # noqa: E501

class DescribeClusterConfigurationResponseContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, cluster_configuration=None):  # noqa: E501
        """DescribeClusterConfigurationResponseContent - a model defined in OpenAPI

        :param cluster_configuration: The cluster_configuration of this DescribeClusterConfigurationResponseContent.  # noqa: E501
        :type cluster_configuration: ClusterConfigurationStructure
        """
        self.openapi_types = {
            'cluster_configuration': ClusterConfigurationStructure
        }

        self.attribute_map = {
            'cluster_configuration': 'clusterConfiguration'
        }

        self._cluster_configuration = cluster_configuration

    @classmethod
    def from_dict(cls, dikt) -> 'DescribeClusterConfigurationResponseContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DescribeClusterConfigurationResponseContent of this DescribeClusterConfigurationResponseContent.  # noqa: E501
        :rtype: DescribeClusterConfigurationResponseContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cluster_configuration(self):
        """Gets the cluster_configuration of this DescribeClusterConfigurationResponseContent.


        :return: The cluster_configuration of this DescribeClusterConfigurationResponseContent.
        :rtype: ClusterConfigurationStructure
        """
        return self._cluster_configuration

    @cluster_configuration.setter
    def cluster_configuration(self, cluster_configuration):
        """Sets the cluster_configuration of this DescribeClusterConfigurationResponseContent.


        :param cluster_configuration: The cluster_configuration of this DescribeClusterConfigurationResponseContent.
        :type cluster_configuration: ClusterConfigurationStructure
        """
        if cluster_configuration is None:
            raise ValueError("Invalid value for `cluster_configuration`, must not be `None`")  # noqa: E501

        self._cluster_configuration = cluster_configuration
