# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.compute_fleet_status import ComputeFleetStatus
from openapi_server import util

from openapi_server.models.compute_fleet_status import ComputeFleetStatus  # noqa: E501

class DescribeComputeFleetStatusResponseContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, status=None):  # noqa: E501
        """DescribeComputeFleetStatusResponseContent - a model defined in OpenAPI

        :param status: The status of this DescribeComputeFleetStatusResponseContent.  # noqa: E501
        :type status: ComputeFleetStatus
        """
        self.openapi_types = {
            'status': ComputeFleetStatus
        }

        self.attribute_map = {
            'status': 'status'
        }

        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'DescribeComputeFleetStatusResponseContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DescribeComputeFleetStatusResponseContent of this DescribeComputeFleetStatusResponseContent.  # noqa: E501
        :rtype: DescribeComputeFleetStatusResponseContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self):
        """Gets the status of this DescribeComputeFleetStatusResponseContent.


        :return: The status of this DescribeComputeFleetStatusResponseContent.
        :rtype: ComputeFleetStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this DescribeComputeFleetStatusResponseContent.


        :param status: The status of this DescribeComputeFleetStatusResponseContent.
        :type status: ComputeFleetStatus
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status
