# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Ec2AmiState(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    PENDING = "pending"
    AVAILABLE = "available"
    INVALID = "invalid"
    DEREGISTERED = "deregistered"
    TRANSIENT = "transient"
    FAILED = "failed"
    ERROR = "error"
    def __init__(self):  # noqa: E501
        """Ec2AmiState - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'Ec2AmiState':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Ec2AmiState of this Ec2AmiState.  # noqa: E501
        :rtype: Ec2AmiState
        """
        return util.deserialize_model(dikt, cls)
