# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ImageStatusFilteringOptions(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    DELETE_COMPLETE = "DELETE_COMPLETE"
    def __init__(self):  # noqa: E501
        """ImageStatusFilteringOptions - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ImageStatusFilteringOptions':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ImageStatusFilteringOptions of this ImageStatusFilteringOptions.  # noqa: E501
        :rtype: ImageStatusFilteringOptions
        """
        return util.deserialize_model(dikt, cls)
