# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.ami_info import AmiInfo
from openapi_server import util

from openapi_server.models.ami_info import AmiInfo  # noqa: E501

class ListOfficialImagesResponseContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, next_token=None, items=None):  # noqa: E501
        """ListOfficialImagesResponseContent - a model defined in OpenAPI

        :param next_token: The next_token of this ListOfficialImagesResponseContent.  # noqa: E501
        :type next_token: str
        :param items: The items of this ListOfficialImagesResponseContent.  # noqa: E501
        :type items: List[AmiInfo]
        """
        self.openapi_types = {
            'next_token': str,
            'items': List[AmiInfo]
        }

        self.attribute_map = {
            'next_token': 'nextToken',
            'items': 'items'
        }

        self._next_token = next_token
        self._items = items

    @classmethod
    def from_dict(cls, dikt) -> 'ListOfficialImagesResponseContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ListOfficialImagesResponseContent of this ListOfficialImagesResponseContent.  # noqa: E501
        :rtype: ListOfficialImagesResponseContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def next_token(self):
        """Gets the next_token of this ListOfficialImagesResponseContent.


        :return: The next_token of this ListOfficialImagesResponseContent.
        :rtype: str
        """
        return self._next_token

    @next_token.setter
    def next_token(self, next_token):
        """Sets the next_token of this ListOfficialImagesResponseContent.


        :param next_token: The next_token of this ListOfficialImagesResponseContent.
        :type next_token: str
        """

        self._next_token = next_token

    @property
    def items(self):
        """Gets the items of this ListOfficialImagesResponseContent.


        :return: The items of this ListOfficialImagesResponseContent.
        :rtype: List[AmiInfo]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this ListOfficialImagesResponseContent.


        :param items: The items of this ListOfficialImagesResponseContent.
        :type items: List[AmiInfo]
        """
        if items is None:
            raise ValueError("Invalid value for `items`, must not be `None`")  # noqa: E501

        self._items = items
