# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.compute_fleet_status_input import ComputeFleetStatusInput
from openapi_server import util

from openapi_server.models.compute_fleet_status_input import ComputeFleetStatusInput  # noqa: E501

class UpdateComputeFleetStatusRequestContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, status=None):  # noqa: E501
        """UpdateComputeFleetStatusRequestContent - a model defined in OpenAPI

        :param status: The status of this UpdateComputeFleetStatusRequestContent.  # noqa: E501
        :type status: ComputeFleetStatusInput
        """
        self.openapi_types = {
            'status': ComputeFleetStatusInput
        }

        self.attribute_map = {
            'status': 'status'
        }

        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateComputeFleetStatusRequestContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateComputeFleetStatusRequestContent of this UpdateComputeFleetStatusRequestContent.  # noqa: E501
        :rtype: UpdateComputeFleetStatusRequestContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self):
        """Gets the status of this UpdateComputeFleetStatusRequestContent.


        :return: The status of this UpdateComputeFleetStatusRequestContent.
        :rtype: ComputeFleetStatusInput
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this UpdateComputeFleetStatusRequestContent.


        :param status: The status of this UpdateComputeFleetStatusRequestContent.
        :type status: ComputeFleetStatusInput
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status
