# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.config_validation_message import ConfigValidationMessage
from openapi_server.models.update_error import UpdateError
from openapi_server import util

from openapi_server.models.config_validation_message import ConfigValidationMessage  # noqa: E501
from openapi_server.models.update_error import UpdateError  # noqa: E501

class UpdateClusterBadRequestExceptionResponseContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, configuration_validation_errors=None, message=None, update_validation_errors=None):  # noqa: E501
        """UpdateClusterBadRequestExceptionResponseContent - a model defined in OpenAPI

        :param configuration_validation_errors: The configuration_validation_errors of this UpdateClusterBadRequestExceptionResponseContent.  # noqa: E501
        :type configuration_validation_errors: List[ConfigValidationMessage]
        :param message: The message of this UpdateClusterBadRequestExceptionResponseContent.  # noqa: E501
        :type message: str
        :param update_validation_errors: The update_validation_errors of this UpdateClusterBadRequestExceptionResponseContent.  # noqa: E501
        :type update_validation_errors: List[UpdateError]
        """
        self.openapi_types = {
            'configuration_validation_errors': List[ConfigValidationMessage],
            'message': str,
            'update_validation_errors': List[UpdateError]
        }

        self.attribute_map = {
            'configuration_validation_errors': 'configurationValidationErrors',
            'message': 'message',
            'update_validation_errors': 'updateValidationErrors'
        }

        self._configuration_validation_errors = configuration_validation_errors
        self._message = message
        self._update_validation_errors = update_validation_errors

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateClusterBadRequestExceptionResponseContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateClusterBadRequestExceptionResponseContent of this UpdateClusterBadRequestExceptionResponseContent.  # noqa: E501
        :rtype: UpdateClusterBadRequestExceptionResponseContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def configuration_validation_errors(self):
        """Gets the configuration_validation_errors of this UpdateClusterBadRequestExceptionResponseContent.


        :return: The configuration_validation_errors of this UpdateClusterBadRequestExceptionResponseContent.
        :rtype: List[ConfigValidationMessage]
        """
        return self._configuration_validation_errors

    @configuration_validation_errors.setter
    def configuration_validation_errors(self, configuration_validation_errors):
        """Sets the configuration_validation_errors of this UpdateClusterBadRequestExceptionResponseContent.


        :param configuration_validation_errors: The configuration_validation_errors of this UpdateClusterBadRequestExceptionResponseContent.
        :type configuration_validation_errors: List[ConfigValidationMessage]
        """

        self._configuration_validation_errors = configuration_validation_errors

    @property
    def message(self):
        """Gets the message of this UpdateClusterBadRequestExceptionResponseContent.


        :return: The message of this UpdateClusterBadRequestExceptionResponseContent.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this UpdateClusterBadRequestExceptionResponseContent.


        :param message: The message of this UpdateClusterBadRequestExceptionResponseContent.
        :type message: str
        """

        self._message = message

    @property
    def update_validation_errors(self):
        """Gets the update_validation_errors of this UpdateClusterBadRequestExceptionResponseContent.


        :return: The update_validation_errors of this UpdateClusterBadRequestExceptionResponseContent.
        :rtype: List[UpdateError]
        """
        return self._update_validation_errors

    @update_validation_errors.setter
    def update_validation_errors(self, update_validation_errors):
        """Sets the update_validation_errors of this UpdateClusterBadRequestExceptionResponseContent.


        :param update_validation_errors: The update_validation_errors of this UpdateClusterBadRequestExceptionResponseContent.
        :type update_validation_errors: List[UpdateError]
        """

        self._update_validation_errors = update_validation_errors
