# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class UpdateError(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, error_code=None, message=None):  # noqa: E501
        """UpdateError - a model defined in OpenAPI

        :param error_code: The error_code of this UpdateError.  # noqa: E501
        :type error_code: str
        :param message: The message of this UpdateError.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {
            'error_code': str,
            'message': str
        }

        self.attribute_map = {
            'error_code': 'errorCode',
            'message': 'message'
        }

        self._error_code = error_code
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateError':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateError of this UpdateError.  # noqa: E501
        :rtype: UpdateError
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error_code(self):
        """Gets the error_code of this UpdateError.


        :return: The error_code of this UpdateError.
        :rtype: str
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code):
        """Sets the error_code of this UpdateError.


        :param error_code: The error_code of this UpdateError.
        :type error_code: str
        """

        self._error_code = error_code

    @property
    def message(self):
        """Gets the message of this UpdateError.


        :return: The message of this UpdateError.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this UpdateError.


        :param message: The message of this UpdateError.
        :type message: str
        """

        self._message = message
