# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.cluster_info_summary import ClusterInfoSummary
from openapi_server import util

from openapi_server.models.cluster_info_summary import ClusterInfoSummary  # noqa: E501

class UpdateClusterResponseContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, cluster=None):  # noqa: E501
        """UpdateClusterResponseContent - a model defined in OpenAPI

        :param cluster: The cluster of this UpdateClusterResponseContent.  # noqa: E501
        :type cluster: ClusterInfoSummary
        """
        self.openapi_types = {
            'cluster': ClusterInfoSummary
        }

        self.attribute_map = {
            'cluster': 'cluster'
        }

        self._cluster = cluster

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateClusterResponseContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateClusterResponseContent of this UpdateClusterResponseContent.  # noqa: E501
        :rtype: UpdateClusterResponseContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cluster(self):
        """Gets the cluster of this UpdateClusterResponseContent.


        :return: The cluster of this UpdateClusterResponseContent.
        :rtype: ClusterInfoSummary
        """
        return self._cluster

    @cluster.setter
    def cluster(self, cluster):
        """Sets the cluster of this UpdateClusterResponseContent.


        :param cluster: The cluster of this UpdateClusterResponseContent.
        :type cluster: ClusterInfoSummary
        """
        if cluster is None:
            raise ValueError("Invalid value for `cluster`, must not be `None`")  # noqa: E501

        self._cluster = cluster
