plugins {
    id("org.openapi.generator") version "5.0.0"
}

openApiValidate {
    inputSpec = "$projectDir/model/openapi/ParallelCluster.openapi.json".toString()
}

task generatePythonServer(
        type: org.openapitools.generator.gradle.plugin.tasks.GenerateTask,
        dependsOn: ['buildModel', 'openApiValidate']
) {
    outputs.upToDateWhen { false }
    outputs.cacheIf { false }
    generatorName = "python-flask"
    inputSpec = "$projectDir/model/openapi/ParallelCluster.openapi.json".toString()
    outputDir = "$projectDir/generated/python-server".toString()
    configOptions = [
            disallowAdditionalPropertiesIfNotPresent: "false"
    ]
}

task generatePythonClient(
        type: org.openapitools.generator.gradle.plugin.tasks.GenerateTask,
        dependsOn: ['buildModel', 'openApiValidate']
) {
    outputs.upToDateWhen { false }
    outputs.cacheIf { false }
    generatorName = "python"
    inputSpec = "$projectDir/model/openapi/ParallelCluster.openapi.json".toString()
    outputDir = "$projectDir/generated/python-client".toString()
}

task buildModel(type:Exec) {
    workingDir "$projectDir/model"
    commandLine "./build-model.sh"
}

task swaggerUI(type:Exec) {
    workingDir "$projectDir/model"
    commandLine "./run-swagger-ui.sh"
}

task redoc(type:Exec) {
    workingDir "$projectDir/model"
    commandLine "./generate-redoc-bundle.sh"
}
